import { CompetitorDef } from "../types";

export const COMPETITORS: CompetitorDef[] = [
  {
    slug: "ens",
    name: "ENS",
    twitterHandle: "ensdomains",
    tokenSymbol: "ENS",
    coingeckoId: "ethereum-name-service",
    defiLlamaSlug: "ens",
    dappRadarSlug: "ethereum-name-service",
    website: "https://ens.domains",
  },
  {
    slug: "unstoppable",
    name: "Unstoppable Domains",
    twitterHandle: "unstoppableweb",
    website: "https://unstoppabledomains.com",
  },
  {
    slug: "spaceid",
    name: "SpaceID",
    twitterHandle: "SpaceIDProtocol",
    tokenSymbol: "ID",
    coingeckoId: "space-id",
    defiLlamaSlug: "space-id",
    website: "https://space.id",
  },
  {
    slug: "bonfida",
    name: "SNS / Bonfida",
    twitterHandle: "bonfida",
    tokenSymbol: "FIDA",
    coingeckoId: "bonfida",
    website: "https://www.sns.id",
  },
  {
    slug: "fio",
    name: "FIO Protocol",
    twitterHandle: "joinFIO",
    tokenSymbol: "FIO",
    coingeckoId: "fio-protocol",
    website: "https://fio.net",
  },
  {
    slug: "handshake",
    name: "Handshake",
    twitterHandle: "HNS_protocol",
    tokenSymbol: "HNS",
    coingeckoId: "handshake",
    dappRadarSlug: "handshake",
    website: "https://handshake.org",
  },
  {
    slug: "freename",
    name: "Freename",
    twitterHandle: "FreenameIO",
    website: "https://freename.io",
  },
  {
    slug: "lens",
    name: "Lens Protocol",
    twitterHandle: "LensProtocol",
    tokenSymbol: "GRASS",
    coingeckoId: "lens-protocol",
    website: "https://lens.xyz",
  },
  {
    slug: "suns",
    name: "SuNS",
    twitterHandle: "SuNSdapp",
    tokenSymbol: "SNS",
    coingeckoId: "synesis-one",
    defiLlamaSlug: "suns",
    website: "https://suns.io",
  },
  {
    slug: "starknetid",
    name: "Starknet ID",
    twitterHandle: "Starknet_id",
    website: "https://starknet.id",
  },
  {
    slug: "basenames",
    name: "Basenames",
    twitterHandle: "BuildOnBase",
    dappRadarSlug: "basenames",
    website: "https://base.org",
  },
  {
    slug: "zns",
    name: "ZNS (Zilliqa)",
    twitterHandle: "zilliqa",
    tokenSymbol: "ZIL",
    coingeckoId: "zilliqa",
    website: "https://zilliqa.com",
  },
  {
    slug: "nearns",
    name: "NEAR NS",
    twitterHandle: "NEARProtocol",
    tokenSymbol: "NEAR",
    coingeckoId: "near",
    defiLlamaSlug: "near",
    website: "https://near.org",
  },
  {
    slug: "ans",
    name: "ANS (Avalanche)",
    twitterHandle: "avax_ans",
    website: "https://avvy.domains",
  },
  {
    slug: "clusters",
    name: "Clusters",
    twitterHandle: "ClustersXYZ",
    website: "https://clusters.xyz",
  },
  {
    slug: "alldomains",
    name: "Alldomains",
    twitterHandle: "AlldomainsTLD",
    dappRadarSlug: "alldomains",
    website: "https://alldomains.id",
  },
];
