export const AGENT_SEEDS = [
  {
    slug: "competitive_intel",
    name: "Competitive Intelligence",
    type: "competitive_intel",
    schedule: "0 */6 * * *",
    description: "Monitors 16 competitors every 6 hours: Twitter activity, token prices, TVL, on-chain data",
  },
  {
    slug: "social_media",
    name: "Social Media",
    type: "social_media",
    schedule: "0 */4 * * *",
    description: "Creates and posts content to Twitter and Discord every 4 hours",
  },
  {
    slug: "business_dev",
    name: "Business Development",
    type: "business_dev",
    schedule: "0 */12 * * *",
    description: "Researches prospects, sends personalized outreach, manages BD pipeline",
  },
  {
    slug: "community",
    name: "Community Monitor",
    type: "community",
    schedule: "*/30 * * * *",
    description: "Reads Twitter mentions and Discord every 30 minutes, replies to questions, spots ambassadors",
  },
  {
    slug: "devrel",
    name: "Developer Relations",
    type: "devrel",
    schedule: "0 */8 * * *",
    description: "Monitors hackathons, developer conversations, creates technical content",
  },
  {
    slug: "analytics",
    name: "Analytics & Briefing",
    type: "analytics",
    schedule: "0 9 * * *",
    description: "Compiles a full daily morning briefing emailed to you every morning",
  },
  {
    slug: "brand",
    name: "Brand Guardian",
    type: "brand",
    schedule: "0 10 * * *",
    description: "Maintains voice guidelines and audits content quality daily",
  },
  {
    slug: "enterprise",
    name: "Enterprise Outreach",
    type: "enterprise",
    schedule: "0 8 * * *",
    description: "Targets Fortune 500 companies with personalized outreach daily",
  },
  {
    slug: "newsletter",
    name: "Newsletter Compiler",
    type: "newsletter",
    schedule: "0 9 * * 1",
    description: "Compiles the weekly newsletter from all agent discoveries every Monday",
  },
] as const;
